### ISSUE TITLE
fields do not update when initailValues is changed

### ISSUE THREAD

**Issue by VatsaPatel** [selbekk/calidation#12]
fields do not update when initailValues is changed. I am building Edit Data form in which first I need to fetch data through API in componentDidMount(). Before the data is fetched, the form is re-rendered 2 times & when new values are inserted into initialValues, in the 3rd render fields do not update. It works great when const is used.

**Comment by sgriffin916** [comment]
I just add a { this.props.data !== undefined && <FormComponent.... /> to prevent it from rendering without any data.  It works fine if you limit it to only render once data exists.

**Comment by VatsaPatel** [comment]
Thank you for quick response. Will try and let you know.
