### ISSUE TITLE
Suggestion for Calculated Fields

### ISSUE THREAD

**Issue by CharlieMarket** [selbekk/calidation#13]
How can I calculate values for "read only" fields ? For example, I want a field with result of adding field1 plus field2 values.
Is there any way to get fields before "submit" to calculated fields ?

**Comment by selbekk** [comment]
Hi!

I'm not sure if I understand your question correctly. Why would you want to validate a calculated field?

If you want to get the form fields in your `render` method, they are available to you via the `fields` argument:

```js
const Example = () => (
  <FormValidation config={...}>
    {({ fields }) => (
      <>
        <input name="field1" value={fields.field1} />
        <input name="field2" value={fields.field2} />
        <input disabled name="field3" value={fields.field1 + fields.field2} />
      </>
    )}
  </FormValidation>
);
```

Hope this helps! If not, I need a bit more information.
