### ISSUE TITLE
initialValue reset on componentDidMount

### ISSUE THREAD

**Issue by elloux** [selbekk/calidation#17]
I am using this library to validad a form. This is a compound form, so what I do is that the Father is alive certain fields are going to be visible and validated if he is not alive the the fields will not be visible and will not be validated.

In my component the input value is this.state.lastname, the lastname is an empty string in the constructor, but when the componentDidMount function gets the father data from the server then the this.state.lastname is updated, so the initialValues object value changes. Is there a way to reset the initialValue when the new value of the this.state.lastname is changed.
I am using the optional initialValue, because if in my input i put `value={this.state.lastname}`, then if the value of the input is not empty but the onChange has not been fired, the error label appears even if the input is not empty.

This is just an example with one input field.

    export default class Father extends React.Component {
      constructor (props) {
        super(props)
        this.state = {
          lastname: ''
        }
      }

      componentDidMount() {
        this.getInfo();
      }

      getInfo() {
        var self = this;

        $.ajax({
          url: '/user/' + self.props.coduser,
          success: function(data) {
            if (data) {
              self.setState({
                lastname: data.lastname
              });
            }
          },
          error: function(xhr, status, error) {
            alert('Erorrr', status, xhr, error);
          }
        });
      }

      handleChange(e) {
        var input_name = e.target.name;
        var value = e.target.type ==='checkbox' ? e.target.checked : e.target.value;
        this.setState({ [input_name]: value });
      }
      
      render () {
        const config = {
          lastname: {
            isRequired: '¡Last name is required!',
          },
        };

        var initialValues = {
          lastname: this.state.lastname
        };

        render (
          <Validation config={config} initialValues={initialValues}>
            {({ fields, errors, submitted }) => (
              <React.Fragment>
                <input type="text"
                           className="form-control"
                           name="lastname"
                           id="lastname"
                           value={fields.lastname}
                           onChange={this.handleChange.bind(self)} />
              </React.Fragment>
            )}
          </Validation>
        );
      }
    }

**Comment by lisatassone** [comment]
@elloux If you look at the source code for [Validation.js](https://github.com/selbekk/calidation/blob/master/src/Validation.js#L36) you can see it only gets populated with `initialValues` on `componentDidMount`. There are no subsequent checks on further lifecycle methods and I'd say that's by design. If you supply the form with an `initialValues` object that gets updated it could overwrite fields that may have been edited. Checking the repo issue history, there's been a few others who have logged it as well because one may expect the change to cascade through. They have got around it by simply not rendering the form till the object has been populated with data.

**Comment by iyobo** [comment]
How I get around this is, for forms that require this, I track the current context for each form in the render function i.e

```

render {
<Validation config={config} initialValues={initialValues}>
        {(ctx) => {
            this.formContext = ctx
            const { fields, errors, submitted } = ctx;
```

Then I can use this form context anywhere within the component, ensuring to always check for existence. e.g

```
doAsync().then((newValue)=>{
   const delta = {foo: newValue};
   this.setState(delta);
   if(formContext) formContext.setField(delta);
});

```

**Comment by lisatassone** [comment]
@iyobo That's not a bad way to handle a few different scenarios actually, such as submitting the form outside the context of the Form component. Thanks for sharing, seems obvious now!

**Comment by bshiroya** [comment]
> I am using this library to validad a form. This is a compound form, so what I do is that the Father is alive certain fields are going to be visible and validated if he is not alive the the fields will not be visible and will not be validated.
> 
> In my component the input value is this.state.lastname, the lastname is an empty string in the constructor, but when the componentDidMount function gets the father data from the server then the this.state.lastname is updated, so the initialValues object value changes. Is there a way to reset the initialValue when the new value of the this.state.lastname is changed.
> I am using the optional initialValue, because if in my input i put `value={this.state.lastname}`, then if the value of the input is not empty but the onChange has not been fired, the error label appears even if the input is not empty.
> 
> This is just an example with one input field.
> 
> ```
> export default class Father extends React.Component {
>   constructor (props) {
>     super(props)
>     this.state = {
>       lastname: ''
>     }
>   }
> 
>   componentDidMount() {
>     this.getInfo();
>   }
> 
>   getInfo() {
>     var self = this;
> 
>     $.ajax({
>       url: '/user/' + self.props.coduser,
>       success: function(data) {
>         if (data) {
>           self.setState({
>             lastname: data.lastname
>           });
>         }
>       },
>       error: function(xhr, status, error) {
>         alert('Erorrr', status, xhr, error);
>       }
>     });
>   }
> 
>   handleChange(e) {
>     var input_name = e.target.name;
>     var value = e.target.type ==='checkbox' ? e.target.checked : e.target.value;
>     this.setState({ [input_name]: value });
>   }
>   
>   render () {
>     const config = {
>       lastname: {
>         isRequired: '¡Last name is required!',
>       },
>     };
> 
>     var initialValues = {
>       lastname: this.state.lastname
>     };
> 
>     render (
>       <Validation config={config} initialValues={initialValues}>
>         {({ fields, errors, submitted }) => (
>           <React.Fragment>
>             <input type="text"
>                        className="form-control"
>                        name="lastname"
>                        id="lastname"
>                        value={fields.lastname}
>                        onChange={this.handleChange.bind(self)} />
>           </React.Fragment>
>         )}
>       </Validation>
>     );
>   }
> }
> ```
What is soluton same problem at my app while edit data    ?

**Comment by ArrayKnight** [comment]
As previously discussed, the `initialValues` object shouldn't be modified, as these changes are not propagated down. If it needs to be, the form render should be delayed until the actual initial values have been fetched.

If you have form sections that are dependent on other form sections, breaking them into separate `Validation` blocks with separate `config`s and `initialValues` is the way to go.
