### ISSUE TITLE
Calling onSubmit programmatically

### ISSUE THREAD

**Issue by Resin01** [selbekk/calidation#19]
Really great package. I use it for rendering user build forms, and it works like a charm.
One thing I seem to be missing though. I cannot seem to find a way to trigger onSubmit manually. If the user hits enter in a text area I want it to submit.
Is there a way to do this that I haven't found? Or is it perhaps a planned feature?

Thanks

**Comment by selbekk** [comment]
Hi!

Thanks for creating this issue. This is currently not supported, but I don't mind adding the feature.

**Comment by selbekk** [comment]
Added the feature on master, but I won't be able to release it until tomorrow or so.

**Comment by Resin01** [comment]
Awesome!
Would you mind updating NPM? Cannot get the newest changes.

**Comment by selbekk** [comment]
There you go ❤️
