### ISSUE TITLE
Should have a way to inject errors onto fields in onSubmit

### ISSUE THREAD

**Issue by iyobo** [selbekk/calidation#25]
Sometimes, some fields can only be determines invalid after an async call.
In scenarios like this, it is necessary to be able to inject an error into a particular field upon determining this.

**Comment by iyobo** [comment]
## Everyone:
if anyone is interested, I submitted a PR that adds a whole bunch of features to calidation.

## PR
https://github.com/selbekk/calidation/pull/27

## Issues Resolved
https://github.com/selbekk/calidation/issues/28 - Can now inject custom Validators directly into Form/Validation Form component as **extendValidators**. Useful for on-the-fly custom validators that have no use or business being defined somewhere else in some provider...perhaps because it needs to work with some local variables an other states.

https://github.com/selbekk/calidation/issues/26 - All custom validators now have access to more contextual information needed for validation. particularly all field values and all active errors.

https://github.com/selbekk/calidation/issues/25 - The crown addition; A new function setErrors(...) has been added to the formContext. With this, you can now set errors programmatically, both in form component func AND onSubmit...much like setField(...).

Look at the new Readme.md in the PR to understand what the changes are.

The tests need to be updated and I haven't had time to look at it but it works.

Because I needed this out in the wilds quick, I had to publish my fork under another project name: calidation-kindly. Feel free to use that if you want these improvements right now.

**Comment by selbekk** [comment]
Hi! Sorry for not seeing this right away - I was on vacation.

Great additions, let me look at them tomorrow.

Remember, you can always npm install your forked version directly without publishing it.

**Comment by iyobo** [comment]
Npm behavior with GitHub projects isn't all that stable TBH. Sometimes it just randomly deletes the module and you have to run `npm i` again at odd times as it throws "cannot resolve module" errors.

**Comment by selbekk** [comment]
Hm, that’s not my experience - but feel free to do what suits you best.

**Comment by selbekk** [comment]
Okay, so I've finally got a few minutes 😅 

I understand the challenge you're getting at - however, it's not super simple to solve. Here's why:

Validation is run on every change event. By setting an error programmatically, you'd either introduce a lot of complexity trying to keep those "programmatically set" errors when a "native" change event occurs, or you'd lose your programmatically set error on the next change event.

There's a few ways to solve this. My go-to approach is adding another field to my config (i.e. `emailAsync`), and setting the value programmatically to something that would fail its validators. For example:

```js
const config = {
  email: {
    isRequired: 'You need to fill out your email',
    isEmail: 'You need to fill out a valid email',
  },
  emailAsync: {
    isEqual: { 
      message: 'You need to fill out an ACTUALLY valid email',
      value: 'INVALID_EMAIL',
    },
};
```

The best approach would probably be to create something like an "async validator", which would take an async function which would resolve at some point.

**Comment by iyobo** [comment]
@selbekk setting errors don't need to be persisted.
In fact, they shouldn't.

E.g Using a login form for example, if after async call the username doesn't exist, I should be able to see my field error saying it doesn't exist. But the moment you start typing something else, it makes sense that the error clears...as previous error message no longer applies to current input.

I already solve this in my branch by passing a setError function into the formContext.
