### ISSUE TITLE
Custom Validators should have access to full form context

### ISSUE THREAD

**Issue by iyobo** [selbekk/calidation#26]

**Comment by iyobo** [comment]
Added PR

**Comment by iyobo** [comment]
## Everyone:
if anyone is interested, I submitted a PR that adds a whole bunch of features to calidation.

## PR
https://github.com/selbekk/calidation/pull/27

## Issues Resolved
https://github.com/selbekk/calidation/issues/28 - Can now inject custom Validators directly into Form/Validation Form component as **extendValidators**. Useful for on-the-fly custom validators that have no use or business being defined somewhere else in some provider...perhaps because it needs to work with some local variables an other states.

https://github.com/selbekk/calidation/issues/26 - All custom validators now have access to more contextual information needed for validation. particularly all field values and all active errors.

https://github.com/selbekk/calidation/issues/25 - The crown addition; A new function setErrors(...) has been added to the formContext. With this, you can now set errors programmatically, both in form component func AND onSubmit...much like setField(...).

Look at the new Readme.md in the PR to understand what the changes are.

The tests need to be updated and I haven't had time to look at it but it works.

Because I needed this out in the wilds quick, I had to publish my fork under another project name: calidation-kindly. Feel free to use that if you want these improvements right now.

**Comment by aulin** [comment]
Any chance this will be merged? I have the same issue.

**Comment by selbekk** [comment]
Coming up!
