### ISSUE TITLE
Accessing validation state externally

### ISSUE THREAD

**Issue by DynamicArray** [selbekk/calidation#29]
Is it possible to get the current validation state from another component? Or through some event? My scenario does not involve a form submission, so I can't do it there.

Ideally, something in a useEffect hook when unmounting the component would be perfect.

**Comment by selbekk** [comment]
Hi!

I'm looking into introducing some sort of hooks for this library. 

You can always get the current validation state by accessing the errors object, and checking that all keys are empty.
