### ISSUE TITLE
How to check if 2 passwords match?

### ISSUE THREAD

**Issue by igghera** [selbekk/calidation#3]
Hi and thanks for this library, it's so good! 

I'm using it for the first time and I have a (pretty common) use case I can't find in the documentation:
in a registration form, the user has to type a password in a field, and then confirm the password in another field. The validation criterion is that the 2 passwords must match, but I can only find examples of matching a specific value. I don't have access to the fields values in my config options.

Any idea?

**Comment by selbekk** [comment]
Hi!

Thanks for testing out the library! Looks like there's no easy way to do this as of now, but it's been a feature I've been meaning to add. I'll see if I can add it tonight :+1:

**Comment by selbekk** [comment]
Semantic release is pretty cool! :+1:

**Comment by igghera** [comment]
Wow that was quick! Thanks mate, and again, great library! 

And yeah, semantic release is awesome :)

**Comment by selbekk** [comment]
Please let me know if you run into any issues, or if the docs could be clearer at any point. Just make another issue, and I'll get to it as soon as I can

**Comment by igghera** [comment]
Will do. Btw I've just tested this new feature and it works like a charm.
