### ISSUE TITLE
Fix the issue with resetAll mangling the errors and fields objects in the state

### ISSUE THREAD

**Issue by igokul1973** [selbekk/calidation#33]
After the `resetAll` function is run manually, the `errors` and `fields` state objects' first field (by that I mean the first field listed in the config) get transformed into numeric keys and values that represent each letter of that first field. This creates some non-existing non-sensical fields and errors, essentially removing the first field from those objects.
This can be fixed by passing `null` as the second argument to the corresponding reduce functions in the `_this.onReset` return block in the `dist/Form.js`.
Please fix it since I unfortunately do not have time for doing PRs.

**Comment by selbekk** [comment]
Sure, I'll get to it :)
