### ISSUE TITLE
Add isDirty to field validationIf function props

### ISSUE THREAD

**Issue by ArrayKnight** [selbekk/calidation#34]
I'd like to suppress validation on register. And rather than adding an explicit validateOn[De]Register props, I think it would be helpful to track the state of the input via an internal flag which is switched on the first change. Then the validateIf function can accept an isDirty parameter which could be used to suppress validation until the user has made a change.

**Comment by selbekk** [comment]
yeah, that would be a useful addition for sure.

**Comment by ArrayKnight** [comment]
PR added: https://github.com/selbekk/calidation/pull/42
