### ISSUE TITLE
Expose isValid in form context

### ISSUE THREAD

**Issue by ArrayKnight** [selbekk/calidation#35]
Without setting the internal state of the form, expose the isValid param in the form context so a submit button can be disabled (even if the form is not validated on render), please.

**Comment by ArrayKnight** [comment]
It would also be helpful to bypass all of the validateIf conditions

**Comment by selbekk** [comment]
This can be implemented in user space quite easily:

```js
const isValid = Object.values(errors).every(error => !error)
```

Not sure if it needs to be a part of the API, since it's not as well used as in the `onSubmit` handler.

**Comment by selbekk** [comment]
Closing this for now.
