### ISSUE TITLE
Add option to output all errors instead of just the first

### ISSUE THREAD

**Issue by ArrayKnight** [selbekk/calidation#36]
Currently, only the first error is returned (performance reasons?) but it would be nice to be able to get all errors on a field and/or across all fields.

**Comment by ArrayKnight** [comment]
It would also be helpful to bypass all of the validateIf conditions

**Comment by selbekk** [comment]
This is actually by design - you specify the validators in the order they should be run. It's not really a performance issue as a UX issue.

Closing this, but open for your comments :)
