### ISSUE TITLE
How to use resetAll?

### ISSUE THREAD

**Issue by coommark** [selbekk/calidation#37]
Really awesome, this calidation. I swear by it!

However I cannot seem to figure out how to use resetAll() from an onSubmit() success callback. So here is my code, my question is, how to I reset the form?

```
onSubmit = ({ errors, fields, isValid }) => {            
            if (isValid) {
                this.setState({
                    loading: true
                })
                let { name, description } = fields;
                const record = {
                    name: name,
                    description: description
                }
                this.props.mutate({
                    variables: {
                        record
                    }
                }).then((res) => {
                    document.getElementById('permiform').reset();
                    this.setState({
                        error: null,
                        loading: false,
                        showAlert: true
                    })

                }).catch((err) => {
                    console.log({err})
                    this.setState({
                        loading: false
                    })
                })
            }
```
As you can see, I have tried `document.getElementById('permiform').reset();` but it does not work. I can't seem to find how to call `resetAll `in the `.then((res) => {}` callback.

**Comment by selbekk** [comment]
That's true, `resetAll` is not passed to the `onSubmit` handler. I guess I'll be open for a PR adding this.

You can add the function here if you're up for it: https://github.com/selbekk/calidation/blob/master/src/Form.js#L78-L82

**Comment by selbekk** [comment]
You can upgrade to the newest version to get this feature available to you :)

**Comment by fintegri** [comment]
Please give example of resetall
