### ISSUE TITLE
isEmail is not validating as validator.js do

### ISSUE THREAD

**Issue by KenZhouGreat** [selbekk/calidation#54]
Calidation is a such a great package, thanks for your work.

I tried to verify emails like "name@name", and it actually pass the validation test which is not exact same behaviour as validator.js do.

Have I missed something?

Thanks

**Comment by ArrayKnight** [comment]
That was an update in `calidators@2.0.0`, the current version is still pointed at `^1.0.0`. I've gone ahead and created a PR for @selbekk to review.

As for an immediate solution, there are ways for you to override nested dependencies: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

**Comment by KenZhouGreat** [comment]
Thanks Mate. I am looking forward to the new version. I will close this once the new version is released.

Thanks
