### ISSUE TITLE
submitted is set to false again, after you correct value in the invalid field

### ISSUE THREAD

**Issue by Deprivant** [selbekk/calidation#57]
If I submit the form and there are invalid fields in the form (for example all fields are required and user didn't type anything), there are error messages next to invalid fields, and internal submitted state is set to true. That's ok :-). 

But when i correct any invalid field (just type any char in one of invalid field), **submitted state is set to false again**.

Is this expected behavior?

Try your example [https://codesandbox.io/embed/yv17j1qqy9](https://codesandbox.io/embed/yv17j1qqy9)  (from your article https://medium.com/@selbekk/introducing-calidation-7d9a79453f7).

Submit form, there will be 2 errors in Username and Email fields. Type char "a" to field Username. Field Username will be valid, Email is still invalid with error message. That's ok.

And now change Dependencies, set calidation from version 1.2.0 to version 1.16.0 (last) and do the same thing. For this time will disappear error mesage next to email, because submitted state is changed to false in this case, and that's why email field looks valid (no error message)

**Comment by diegomrv** [comment]
I'm also having the same problem, I went and tried different versions and the last version this was working is 1.10.0, after 1.11.0 the submitted state changes to false when you start editing a field so all error messages disappear :(

Went ahead and looked at the code that changes 1.10 to 1.11 but I don't feel that capable of pointing out what could be the problem :P
