### ISSUE TITLE
Is it possible that HTML5 Form Validation has priority before Calidation?

### ISSUE THREAD

**Issue by Deprivant** [selbekk/calidation#59]
Again your own example [https://codesandbox.io/embed/yv17j1qqy9]( https://codesandbox.io/embed/yv17j1qqy9).

Type to **Email field** something incorrect, for example "xx" and hit Submit button.

**It looks that all "modern" types of input, like email, number etc. is validating with default HTML5 validation in the browser, and Calidation is inactive.** 

Only validator isRequired works with all types of input.

**Comment by Deprivant** [comment]
To avoid doing this, attribute **noValidate** must be added to <FormValidation /> component. Maybe Calidation could do it automatically...

**Comment by selbekk** [comment]
Smart, yeah we could add that. Want to create a PR?

**Comment by diegomrv** [comment]
@selbekk hey, there was a small oversight on my PR earlier today... I added the noValidate attribute as "novalidate" (no camelCase) and React isn't adding it to the form. Should I create another PR for that one?
