### ISSUE TITLE
Use of state in setState

### ISSUE THREAD

**Issue by serenata-keith-mifsud** [selbekk/calidation#62]
Calling setField simultaneously from two different components can lead to one overwriting the diff sent by the other with older values. React setState accepts a function giving you the current state, and the diffs should be built using that instead of calculating everything first, then setting the result as the new state.

https://github.com/selbekk/calidation/blob/24e9e0c329e487ab831f8c184007aa399fee5fff/src/Form.js#L147

React talks about this behavior here: https://reactjs.org/docs/react-component.html#setstate

Ideally setField and every call to setStateInternal should look like

```
setField = diff => {
    this.setStateInternal(({ config, dirty, fields }) => {
        const allFields = { ...fields, ...diff };
        const areDirty = {
            ...dirty,
            ...Object.keys(diff).reduce(
                (allDirty, field) => ({
                    ...allDirty,
                    [field]:
                        dirty[field] ||
                        diff[field] !== this.initialValues[field],
                }),
                {},
            ),
        };

        return {
            dirty: areDirty,
            errors: this.validate(config, allFields, areDirty),
            fields: allFields,
        }
    });
}
```

**Comment by selbekk** [comment]
Thanks for raising this issue - that surely was an oversight by us :) Merged, and will be released shortly.
