### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by diegomrv** [selbekk/calidation#64]
Hi!

I was wondering what's the oficial way to have optional fields... I'm wrapping the fields inside `<FormValidation>` and setting my config for the fields that need validation, but if some of other fields are optional, I don't have them available in the fields object.

For now I've just created an "optional" validator that uses the isDirty flag and never returns invalid, but I was wondering if there's a way to do it that I haven't understood from the documentation.

Thanks!

**Comment by serenata-keith-mifsud** [comment]
giving the property an empty object in config also seems to do the trick

**Comment by diegomrv** [comment]
OMG you're right, don't know why I didn't try that 🤦🏽‍♂️
