### ISSUE TITLE
Can't use validation with custom selects and date picker

### ISSUE THREAD

**Issue by dagenius007** [selbekk/calidation#65]

**Comment by selbekk** [comment]
Hi! Could you please provide some more context or a reproducible example? It's a bit hard to help implement a feature without more to go on than "doesn't work". ;-) 

You're probably struggling with that the `change` event handlers not being triggered. You can trigger them manually by tapping into whatever the `onChange` event handler is on your custom select or date picker, and calling the `setField` function manually.

**Comment by selbekk** [comment]
I'm closing this, but I'd be happy to re-open it if you can't work around it for some reason.

**Comment by Orsunmigbare** [comment]
```
<FormValidation>
  {({ setField }) => (
     <Input
                                    required
                                    name="btc_amount"
                                    autoFocus
                                    value={fields.btc_amount}
                                    onChange={e => {
                                        const btc_in_dollars = bitcoin_in_dolars * parseFloat(e.target.value);
                                        console.log(btc_in_dollars)
                                        setField({ btc_in_dollars })
                                    }}
                                 
                                />
  )}
</FormValidation>
```


setField is not working. any help?

**Comment by selbekk** [comment]
Hi @Orsunmigbare - btc_in_dollars needs to be a part of your form config in order for this to work. Please create a new issue with a reproduction, and I’d love to help you solve the issue
