### ISSUE TITLE
Suggestion for form setup or how to reset submitted?

### ISSUE THREAD

**Issue by sgriffin916** [selbekk/calidation#7]
Love Calidation so far!  One issue I have run into is not having the ability to reset the submitted value back to false.  Maybe how I have my form set up is the issue?  Basically I have a the FormValidation wrapped around a table so that when I click the Edit button, it will display a table row that has form elements in it for the user to edit the data inline, so to speak.  When I click save, it does due the form validation but from that point forward, it will always treat every new row being edited as already having been submitted.  The table rows are being created by mapping over an array of users.

Ideas?

Thanks!

**Comment by selbekk** [comment]
Hi! Thanks for the kind words - and sorry for the very late response!

Sounds like we could add support for resetting the form - I haven't had the chance to implement it yet. 

I'll look into it as soon as possible!

**Comment by selbekk** [comment]
Feature has been added, will be released tomorrow or so.
