### ISSUE TITLE
initialValues does not update the fields object in the state

### ISSUE THREAD

**Issue by sgriffin916** [selbekk/calidation#8]
When I set the initialValues object for my form, the text shows up in my textbox but when I submit my form without changing any of the text in that textbox, it throws an error.  Looking through the code, it appears the issue maybe that the state never gets updated on load?  I am guessing I might be able to do a work-around by using setField. Or was that how initialValues was intended to be used?  Can I get clarification?

Thanks!

**Comment by sgriffin916** [comment]
D'oh!  Disregard.  I realized what I did wrong.  The form loaded with the initial empty object.  I just added a conditional to say that it should not load the form until the props had the data in the object.  Works great now.

**Comment by bshiroya** [comment]
> D'oh! Disregard. I realized what I did wrong. The form loaded with the initial empty object. I just added a conditional to say that it should not load the form until the props had the data in the object. Works great now.

Could you please share withi this solution ?
